language: c
sudo: false
os:
  - osx
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - yasm
      - texinfo
script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       brew update;
       brew install yasm;
    fi
  # On OSX, gcc is a wrapper around clang, so use gcc from homebrew
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]] && [[ "${CC}" == "gcc" ]]; then
       brew install gcc73;
       export CC=gcc-7.3;
       export CXX=g++-7.3;
    fi
  - $CC --version
  - ./autogen.sh
  - ./configure && make && make check
